# Generated by Django - Data migration for Tay Ninh specialties

from django.db import migrations


def create_tayninh_data(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    Product = apps.get_model('shop', 'Product')
    Page = apps.get_model('shop', 'Page')
    
    # Tạo danh mục
    muoi_category = Category.objects.create(
        name='Muối Tây Ninh',
        slug='muoi-tay-ninh',
        description='Các loại muối đặc sản Tây Ninh với hương vị độc đáo, được chế biến từ công thức truyền thống',
        display_order=1
    )
    
    banh_trang_category = Category.objects.create(
        name='Bánh Tráng Tây Ninh',
        slug='banh-trang-tay-ninh',
        description='Bánh tráng Tây Ninh nổi tiếng với độ giòn tan, thơm ngon, được làm thủ công theo phương pháp truyền thống',
        display_order=2
    )
    
    # Tạo sản phẩm Muối
    muoi_products = [
        {
            'name': 'Muối Ớt Tây Ninh',
            'slug': 'muoi-ot-tay-ninh',
            'description': '''Muối ớt Tây Ninh là sự kết hợp hoàn hảo giữa muối rang và ớt tươi xay nhuyễn. 
            
Đặc điểm:
- Vị cay nồng đặc trưng của ớt Tây Ninh
- Màu đỏ tươi tự nhiên
- Độ mặn vừa phải, cay đậm đà
- Không chất bảo quản

Công dụng: Chấm trái cây (xoài, ổi, khế), rau củ luộc, thịt nướng

Trọng lượng: 100g/hộp
Hạn sử dụng: 6 tháng kể từ ngày sản xuất''',
            'price': 35000,
            'priority': 10
        },
        {
            'name': 'Muối Tôm Tây Ninh',
            'slug': 'muoi-tom-tay-ninh',
            'description': '''Muối tôm Tây Ninh được làm từ tôm tươi và muối rang thơm, tạo nên hương vị đặc biệt.

Đặc điểm:
- Tôm tươi được sấy khô và xay nhuyễn
- Hương thơm đặc trưng của tôm biển
- Vị ngọt tự nhiên từ tôm
- Giàu protein và khoáng chất

Công dụng: Chấm trái cây, rau sống, bánh tráng, thịt luộc

Trọng lượng: 100g/hộp
Hạn sử dụng: 6 tháng''',
            'price': 45000,
            'priority': 9
        },
        {
            'name': 'Muối Tiêu Tây Ninh',
            'slug': 'muoi-tieu-tay-ninh',
            'description': '''Muối tiêu Tây Ninh kết hợp muối rang và tiêu đen Tây Ninh nổi tiếng.

Đặc điểm:
- Tiêu đen Tây Ninh xay thô
- Vị cay nồng của tiêu
- Mùi thơm đặc trưng
- Không phẩm màu, không chất bảo quản

Công dụng: Chấm hoa quả, thịt nướng, hải sản, làm gia vị nấu ăn

Trọng lượng: 100g/hộp
Hạn sử dụng: 6 tháng''',
            'price': 40000,
            'priority': 8
        },
        {
            'name': 'Muối Rang Tây Ninh',
            'slug': 'muoi-rang-tay-ninh',
            'description': '''Muối rang truyền thống Tây Ninh, được rang theo công thức gia truyền.

Đặc điểm:
- Muối biển tinh khiết
- Rang khô trên chảo gang
- Màu trắng đẹp, hạt mịn
- Vị mặn thanh, không đắng

Công dụng: Chấm trái cây, làm gia vị, ướp thịt

Trọng lượng: 150g/hộp
Hạn sử dụng: 12 tháng''',
            'price': 25000,
            'priority': 7
        },
        {
            'name': 'Muối Sate Tây Ninh',
            'slug': 'muoi-sate-tay-ninh',
            'description': '''Muối sate Tây Ninh với hương vị cay nồng, thơm lừng đặc trưng.

Đặc điểm:
- Kết hợp sả, tỏi, ớt và các gia vị
- Màu đỏ cam bắt mắt
- Vị cay đậm đà, thơm nồng
- Chế biến thủ công

Công dụng: Chấm hải sản nướng, thịt nướng, lẩu, bún bò

Trọng lượng: 100g/hộp
Hạn sử dụng: 6 tháng''',
            'price': 50000,
            'priority': 6
        },
        {
            'name': 'Muối Tỏi Ớt Tây Ninh',
            'slug': 'muoi-toi-ot-tay-ninh',
            'description': '''Muối tỏi ớt Tây Ninh - sự kết hợp hoàn hảo giữa tỏi và ớt tươi.

Đặc điểm:
- Tỏi tươi và ớt xay nhuyễn
- Vị cay nồng, thơm tỏi
- Màu đỏ cam tự nhiên
- Giàu vitamin và khoáng chất

Công dụng: Chấm thịt nướng, hải sản, rau củ, trộn salad

Trọng lượng: 100g/hộp
Hạn sử dụng: 4 tháng (bảo quản lạnh)''',
            'price': 42000,
            'priority': 5
        },
        {
            'name': 'Muối Mè Rang Tây Ninh',
            'slug': 'muoi-me-rang-tay-ninh',
            'description': '''Muối mè rang Tây Ninh với hương vị thơm béo của mè rang.

Đặc điểm:
- Mè trắng rang vàng thơm
- Xay nhuyễn cùng muối rang
- Vị béo ngậy, thơm mùi mè
- Giàu canxi và chất xơ

Công dụng: Chấm chuối, khoai luộc, rau củ, làm gia vị

Trọng lượng: 100g/hộp
Hạn sử dụng: 6 tháng''',
            'price': 38000,
            'priority': 4
        },
        {
            'name': 'Muối Vừng Đen Tây Ninh',
            'slug': 'muoi-vung-den-tay-ninh',
            'description': '''Muối vừng đen Tây Ninh - sản phẩm cao cấp với vừng đen rang thơm.

Đặc điểm:
- Vừng đen rang chín
- Xay thô giữ nguyên hạt
- Vị béo đặc trưng của vừng đen
- Giàu chất chống oxi hóa

Công dụng: Chấm trái cây, rau củ, làm topping cho món ăn

Trọng lượng: 100g/hộp
Hạn sử dụng: 6 tháng''',
            'price': 48000,
            'priority': 3
        },
        {
            'name': 'Muối Ớt Xanh Tây Ninh',
            'slug': 'muoi-ot-xanh-tay-ninh',
            'description': '''Muối ớt xanh Tây Ninh với vị cay thanh, thơm mát đặc biệt.

Đặc điểm:
- Ớt xanh tươi xay nhuyễn
- Vị cay nhẹ, thanh mát
- Màu xanh tự nhiên
- Hương thơm đặc trưng

Công dụng: Chấm hải sản, thịt luộc, bánh tráng

Trọng lượng: 100g/hộp
Hạn sử dụng: 4 tháng (bảo quản lạnh)''',
            'price': 40000,
            'priority': 2
        },
    ]
    
    for product_data in muoi_products:
        Product.objects.create(
            category=muoi_category,
            is_active=True,
            **product_data
        )
    
    # Tạo sản phẩm Bánh Tráng
    banh_trang_products = [
        {
            'name': 'Bánh Tráng Trộn Tây Ninh',
            'slug': 'banh-trang-tron-tay-ninh',
            'description': '''Bánh tráng trộn Tây Ninh - món ăn vặt được yêu thích nhất.

Đặc điểm:
- Bánh tráng giòn tan
- Trộn sẵn với muối ớt, mè rang
- Vị cay, mặn, ngọt hài hòa
- Đóng gói tiện lợi

Thành phần: Bánh tráng, muối ớt, mè rang, đường, dầu ăn

Trọng lượng: 200g/gói
Hạn sử dụng: 3 tháng''',
            'price': 35000,
            'priority': 10
        },
        {
            'name': 'Bánh Tráng Nướng Mắm Ruốc',
            'slug': 'banh-trang-nuong-mam-ruoc',
            'description': '''Bánh tráng nướng mắm ruốc - hương vị đặc sản miền Tây.

Đặc điểm:
- Nướng trên than hồng
- Phết mắm ruốc đậm đà
- Giòn rụm, thơm lừng
- Ăn liền tiện lợi

Thành phần: Bánh tráng, mắm ruốc, hành phi, mè

Trọng lượng: 150g/gói
Hạn sử dụng: 2 tháng''',
            'price': 45000,
            'priority': 9
        },
        {
            'name': 'Bánh Tráng Phơi Sương',
            'slug': 'banh-trang-phoi-suong',
            'description': '''Bánh tráng phơi sương Tây Ninh - đặc sản cao cấp.

Đặc điểm:
- Phơi qua đêm để hứng sương
- Mỏng, giòn, trong veo
- Vị ngọt tự nhiên
- Làm thủ công 100%

Công dụng: Cuốn thịt nướng, gỏi cuốn, ăn kèm lẩu

Trọng lượng: 300g/gói
Hạn sử dụng: 6 tháng''',
            'price': 55000,
            'priority': 8
        },
        {
            'name': 'Bánh Tráng Dừa Non',
            'slug': 'banh-trang-dua-non',
            'description': '''Bánh tráng dừa non Tây Ninh - hương vị mới lạ, hấp dẫn.

Đặc điểm:
- Cơm dừa non tươi
- Thơm mùi dừa tự nhiên
- Giòn tan, béo ngậy
- Không chất bảo quản

Công dụng: Ăn vặt, cuốn thịt, làm gỏi

Trọng lượng: 250g/gói
Hạn sử dụng: 4 tháng''',
            'price': 48000,
            'priority': 7
        },
        {
            'name': 'Bánh Tráng Mè Đen',
            'slug': 'banh-trang-me-den',
            'description': '''Bánh tráng mè đen Tây Ninh - giàu dinh dưỡng, thơm ngon.

Đặc điểm:
- Rắc mè đen rang thơm
- Giòn rụm, béo mè
- Màu vàng nâu đẹp mắt
- Giàu canxi và vitamin E

Công dụng: Ăn vặt, cuốn thịt nướng

Trọng lượng: 250g/gói
Hạn sử dụng: 5 tháng''',
            'price': 42000,
            'priority': 6
        },
        {
            'name': 'Bánh Tráng Tỏi Phi',
            'slug': 'banh-trang-toi-phi',
            'description': '''Bánh tráng tỏi phi Tây Ninh - thơm lừng, hấp dẫn.

Đặc điểm:
- Tỏi phi vàng giòn
- Thơm nồng mùi tỏi
- Giòn tan, không ngấy
- Gia vị đậm đà

Công dụng: Ăn vặt, nhắm bia, làm quà

Trọng lượng: 200g/gói
Hạn sử dụng: 3 tháng''',
            'price': 40000,
            'priority': 5
        },
        {
            'name': 'Bánh Tráng Cuộn',
            'slug': 'banh-trang-cuon',
            'description': '''Bánh tráng cuộn Tây Ninh - dạng cuộn tiện lợi, dễ ăn.

Đặc điểm:
- Cuộn tròn đều đẹp
- Giòn từng lớp
- Vị ngọt thanh tự nhiên
- Đóng gói hút chân không

Công dụng: Ăn vặt, làm quà tặng

Trọng lượng: 300g/gói
Hạn sử dụng: 6 tháng''',
            'price': 38000,
            'priority': 4
        },
        {
            'name': 'Bánh Tráng Tôm Tươi',
            'slug': 'banh-trang-tom-tuoi',
            'description': '''Bánh tráng tôm tươi Tây Ninh - đặc sản cao cấp.

Đặc điểm:
- Tôm tươi xay nhuyễn
- Thơm mùi tôm biển
- Giòn rụm, ngọt tôm
- Giàu protein

Công dụng: Ăn vặt, nhắm bia, cuốn thịt

Trọng lượng: 200g/gói
Hạn sử dụng: 4 tháng''',
            'price': 52000,
            'priority': 3
        },
        {
            'name': 'Bánh Tráng Sữa',
            'slug': 'banh-trang-sua',
            'description': '''Bánh tráng sữa Tây Ninh - vị ngọt béo hấp dẫn.

Đặc điểm:
- Pha sữa tươi nguyên chất
- Vị ngọt béo của sữa
- Giòn tan, thơm sữa
- Thích hợp cho trẻ em

Công dụng: Ăn vặt, bữa phụ

Trọng lượng: 250g/gói
Hạn sử dụng: 4 tháng''',
            'price': 45000,
            'priority': 2
        },
    ]
    
    for product_data in banh_trang_products:
        Product.objects.create(
            category=banh_trang_category,
            is_active=True,
            **product_data
        )
    
    # Tạo trang Giới Thiệu
    Page.objects.create(
        title='Giới Thiệu',
        slug='gioi-thieu',
        is_active=True,
        content='''
<div class="about-page">
    <h1>Đặc Sản Tây Ninh - Hương Vị Đất Thánh</h1>
    
    <section class="intro">
        <h2>Về Chúng Tôi</h2>
        <p>
            Chào mừng bạn đến với cửa hàng đặc sản Tây Ninh! Chúng tôi tự hào là đơn vị 
            chuyên cung cấp các sản phẩm đặc sản chính gốc từ vùng đất Tây Ninh - mảnh đất 
            thiêng liêng với những món ăn truyền thống đậm đà bản sắc văn hóa miền Tây Nam Bộ.
        </p>
    </section>

    <section class="specialty">
        <h2>Đặc Sản Tây Ninh</h2>
        
        <h3>🧂 Muối Tây Ninh</h3>
        <p>
            Muối Tây Ninh nổi tiếng khắp cả nước với hương vị độc đáo, được chế biến từ 
            công thức gia truyền nhiều đời. Từ muối ớt cay nồng, muối tôm thơm ngon, đến 
            muối tiêu đặc trưng - mỗi loại đều mang trong mình câu chuyện riêng về sự tâm 
            huyết và tình yêu với nghề.
        </p>
        <ul>
            <li><strong>Muối Ớt:</strong> Cay nồng, màu đỏ tươi tự nhiên</li>
            <li><strong>Muối Tôm:</strong> Thơm ngon, giàu dinh dưỡng</li>
            <li><strong>Muối Tiêu:</strong> Kết hợp với tiêu đen Tây Ninh nổi tiếng</li>
            <li><strong>Muối Sate:</strong> Đậm đà, thơm lừng</li>
        </ul>

        <h3>🥞 Bánh Tráng Tây Ninh</h3>
        <p>
            Bánh tráng Tây Ninh được làm hoàn toàn thủ công theo phương pháp truyền thống, 
            đặc biệt là bánh tráng phơi sương - loại bánh được phơi qua đêm để hứng sương, 
            tạo nên độ giòn tan và vị ngọt tự nhiên khó có thể tìm thấy ở bất kỳ nơi nào khác.
        </p>
        <ul>
            <li><strong>Bánh Tráng Phơi Sương:</strong> Mỏng, giòn, trong veo</li>
            <li><strong>Bánh Tráng Trộn:</strong> Món ăn vặt được yêu thích</li>
            <li><strong>Bánh Tráng Nướng:</strong> Thơm lừng, giòn rụm</li>
            <li><strong>Bánh Tráng Dừa Non:</strong> Béo ngậy, thơm dừa</li>
        </ul>
    </section>

    <section class="commitment">
        <h2>Cam Kết Của Chúng Tôi</h2>
        <div class="commitment-list">
            <div class="commitment-item">
                <h4>✓ 100% Sản Phẩm Chính Gốc</h4>
                <p>Tất cả sản phẩm đều được sản xuất tại Tây Ninh theo công thức truyền thống</p>
            </div>
            <div class="commitment-item">
                <h4>✓ An Toàn Vệ Sinh Thực Phẩm</h4>
                <p>Đạt chuẩn ATTP, không chất bảo quản độc hại</p>
            </div>
            <div class="commitment-item">
                <h4>✓ Giá Cả Hợp Lý</h4>
                <p>Giá tận gốc từ nhà sản xuất, không qua trung gian</p>
            </div>
            <div class="commitment-item">
                <h4>✓ Giao Hàng Toàn Quốc</h4>
                <p>Đóng gói cẩn thận, giao hàng nhanh chóng</p>
            </div>
        </div>
    </section>

    <section class="mission">
        <h2>Sứ Mệnh</h2>
        <p>
            Chúng tôi mong muốn đưa hương vị đặc sản Tây Ninh đến với mọi người dân Việt Nam 
            và bạn bè quốc tế, góp phần quảng bá văn hóa ẩm thực đặc sắc của vùng đất Tây Ninh. 
            Mỗi sản phẩm không chỉ là món ăn mà còn là câu chuyện về con người, văn hóa và 
            truyền thống của vùng đất thiêng.
        </p>
    </section>

    <section class="contact-cta">
        <h2>Liên Hệ Với Chúng Tôi</h2>
        <p>
            Để biết thêm thông tin chi tiết về sản phẩm hoặc đặt hàng số lượng lớn, 
            vui lòng liên hệ với chúng tôi qua trang <a href="/lien-he">Liên Hệ</a>.
        </p>
    </section>
</div>
        '''
    )
    
    # Tạo trang Liên Hệ
    Page.objects.create(
        title='Liên Hệ',
        slug='lien-he',
        is_active=True,
        content='''
<div class="contact-page">
    <h1>Liên Hệ Với Chúng Tôi</h1>
    
    <section class="contact-intro">
        <p>
            Chúng tôi luôn sẵn sàng lắng nghe và hỗ trợ bạn. Hãy liên hệ với chúng tôi 
            qua các kênh dưới đây để được tư vấn và phục vụ tốt nhất!
        </p>
    </section>

    <section class="contact-info">
        <h2>Thông Tin Liên Hệ</h2>
        
        <div class="contact-item">
            <h3>📍 Địa Chỉ</h3>
            <p>
                <strong>Cửa hàng chính:</strong><br>
                123 Đường Cách Mạng Tháng 8, Phường 1, Thành phố Tây Ninh, Tỉnh Tây Ninh
            </p>
            <p>
                <strong>Chi nhánh TP.HCM:</strong><br>
                456 Đường Lê Hồng Phong, Phường 2, Quận 10, TP. Hồ Chí Minh
            </p>
        </div>

        <div class="contact-item">
            <h3>📞 Số Điện Thoại</h3>
            <p>
                <strong>Hotline:</strong> <a href="tel:0901234567">0901 234 567</a> (Zalo/Viber)<br>
                <strong>Điện thoại:</strong> <a href="tel:0276123456">(0276) 123 456</a><br>
                <strong>Hỗ trợ khách hàng:</strong> <a href="tel:0902345678">0902 345 678</a>
            </p>
        </div>

        <div class="contact-item">
            <h3>✉️ Email</h3>
            <p>
                <strong>Email chung:</strong> <a href="mailto:info@dacsan-tayninh.vn">info@dacsan-tayninh.vn</a><br>
                <strong>Hỗ trợ khách hàng:</strong> <a href="mailto:support@dacsan-tayninh.vn">support@dacsan-tayninh.vn</a><br>
                <strong>Hợp tác kinh doanh:</strong> <a href="mailto:business@dacsan-tayninh.vn">business@dacsan-tayninh.vn</a>
            </p>
        </div>

        <div class="contact-item">
            <h3>🌐 Mạng Xã Hội</h3>
            <p>
                <strong>Facebook:</strong> <a href="https://facebook.com/dacsantayninh" target="_blank">fb.com/dacsantayninh</a><br>
                <strong>Instagram:</strong> <a href="https://instagram.com/dacsan_tayninh" target="_blank">@dacsan_tayninh</a><br>
                <strong>TikTok:</strong> <a href="https://tiktok.com/@dacsantayninh" target="_blank">@dacsantayninh</a>
            </p>
        </div>
    </section>

    <section class="business-hours">
        <h2>⏰ Giờ Làm Việc</h2>
        <table>
            <tr>
                <td><strong>Thứ 2 - Thứ 6:</strong></td>
                <td>8:00 - 18:00</td>
            </tr>
            <tr>
                <td><strong>Thứ 7:</strong></td>
                <td>8:00 - 17:00</td>
            </tr>
            <tr>
                <td><strong>Chủ Nhật:</strong></td>
                <td>8:00 - 12:00</td>
            </tr>
            <tr>
                <td><strong>Ngày lễ:</strong></td>
                <td>Liên hệ trước</td>
            </tr>
        </table>
    </section>

    <section class="order-info">
        <h2>📦 Thông Tin Đặt Hàng</h2>
        <div class="order-methods">
            <div class="method">
                <h4>Đặt Hàng Online</h4>
                <p>Chọn sản phẩm trên website và đặt hàng trực tiếp</p>
            </div>
            <div class="method">
                <h4>Đặt Hàng Qua Điện Thoại</h4>
                <p>Gọi hotline: 0901 234 567 để được tư vấn và đặt hàng</p>
            </div>
            <div class="method">
                <h4>Đặt Hàng Qua Zalo/Viber</h4>
                <p>Nhắn tin qua Zalo/Viber: 0901 234 567</p>
            </div>
            <div class="method">
                <h4>Mua Trực Tiếp Tại Cửa Hàng</h4>
                <p>Ghé thăm cửa hàng để trải nghiệm và mua sắm trực tiếp</p>
            </div>
        </div>
    </section>

    <section class="shipping-info">
        <h2>🚚 Chính Sách Giao Hàng</h2>
        <ul>
            <li><strong>Miễn phí giao hàng:</strong> Đơn hàng từ 500.000đ trong nội thành TP.HCM và Tây Ninh</li>
            <li><strong>Giao hàng toàn quốc:</strong> Qua các đơn vị vận chuyển uy tín (GHN, GHTK, Viettel Post)</li>
            <li><strong>Thời gian giao hàng:</strong> 1-3 ngày với nội thành, 3-7 ngày với các tỉnh thành khác</li>
            <li><strong>Đóng gói:</strong> Cẩn thận, chắc chắn, đảm bảo sản phẩm nguyên vẹn</li>
        </ul>
    </section>

    <section class="payment-info">
        <h2>💳 Phương Thức Thanh Toán</h2>
        <ul>
            <li>Thanh toán khi nhận hàng (COD)</li>
            <li>Chuyển khoản ngân hàng</li>
            <li>Ví điện tử (MoMo, ZaloPay, VNPay)</li>
            <li>Quẹt thẻ tại cửa hàng</li>
        </ul>
        
        <div class="bank-info">
            <h4>Thông Tin Chuyển Khoản:</h4>
            <p>
                <strong>Ngân hàng:</strong> Vietcombank - Chi nhánh Tây Ninh<br>
                <strong>Số tài khoản:</strong> 0123456789<br>
                <strong>Chủ tài khoản:</strong> CÔNG TY TNHH ĐẶC SẢN TÂY NINH<br>
                <strong>Nội dung:</strong> [Họ tên] - [Số điện thoại] - Đặt hàng
            </p>
        </div>
    </section>

    <section class="faq">
        <h2>❓ Câu Hỏi Thường Gặp</h2>
        <div class="faq-item">
            <h4>Sản phẩm có nguồn gốc từ đâu?</h4>
            <p>Tất cả sản phẩm đều được sản xuất tại Tây Ninh, đảm bảo chính gốc 100%.</p>
        </div>
        <div class="faq-item">
            <h4>Có giao hàng toàn quốc không?</h4>
            <p>Có, chúng tôi giao hàng toàn quốc qua các đơn vị vận chuyển uy tín.</p>
        </div>
        <div class="faq-item">
            <h4>Đặt hàng số lượng lớn có được giảm giá không?</h4>
            <p>Có, vui lòng liên hệ hotline hoặc email để được báo giá ưu đãi cho đơn hàng số lượng lớn.</p>
        </div>
        <div class="faq-item">
            <h4>Sản phẩm có hạn sử dụng bao lâu?</h4>
            <p>Mỗi sản phẩm có hạn sử dụng khác nhau, từ 2-12 tháng tùy loại. Thông tin chi tiết có trên bao bì.</p>
        </div>
    </section>

    <section class="contact-form-note">
        <h2>📝 Gửi Tin Nhắn Cho Chúng Tôi</h2>
        <p>
            Nếu bạn có bất kỳ câu hỏi, góp ý hoặc yêu cầu đặc biệt nào, 
            vui lòng liên hệ qua email hoặc hotline. Chúng tôi sẽ phản hồi trong vòng 24 giờ.
        </p>
        <p class="thank-you">
            <strong>Cảm ơn bạn đã quan tâm đến sản phẩm đặc sản Tây Ninh!</strong>
        </p>
    </section>
</div>
        '''
    )


def remove_tayninh_data(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    Product = apps.get_model('shop', 'Product')
    Page = apps.get_model('shop', 'Page')
    
    # Xóa các trang
    Page.objects.filter(slug__in=['gioi-thieu', 'lien-he']).delete()
    
    # Xóa sản phẩm và danh mục
    Category.objects.filter(slug__in=['muoi-tay-ninh', 'banh-trang-tay-ninh']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_page'),
    ]

    operations = [
        migrations.RunPython(create_tayninh_data, remove_tayninh_data),
    ]
